[project]
name = "strangeloop"
version = "0.0.1"
description = "A recursive and self-referential AI agent framework"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.1.8",
]

[project.scripts]
strangeloop = "strangeloop.cli:cli"

[tool.uv]
package = true